application: contextlinky
<<<<<<< HEAD:app.yaml
version: 3-1
=======
version: 4
>>>>>>> version number test:app.yaml
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: contextlinky.py
- url: /assets
  static_dir: assets
  